//
//  PropertiesManager.h
//  mWidget
//
//  Created by mCloud on 14/12/10.
//  Copyright (c) 2014年 mCloud. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef enum {
    ID =1,
    BUNDLENAME,
    LEFT,
    WIDTH,
    HEIGHT,
    FRAME,
    BACKGROUND,
    VISIBILITY,
    RADIUS,
    TOP,
    MARGIN,
    PADDING,
    FILL_Mode,
    TEXT,
    TEXTCOLOR,
    TEXTALIGN,
    TEXTSIZE,

    TEXTSIZE_NORMAL,
    TEXTSIZE_DISABLE,
    TEXTSIZE_CHECKED,
    TEXTBOLD,
    TEXTITALIC,
    TINTCOLOR,
    EDITABLE,
    HINTTEXT,
    ONCHANGE,
    BORDERWIDTH,
    BORDERSIZE,
    BORDERCOLOR,
    BORDERTYPE,
    BORDER,
    SHAPE,
    BINDING,
    THEME,
    EXPENDDATA,
    ONTAP,
    ONHOLD,
    IMAGE,
    DISABLED,
    DISABLEIMAGE,
    TAPIMAGE,
    TRIANGLECOLOR,
    CELLBACKGROUNDCOLOR,
    ORIENTATION,
    CLEARPROMPT,
    KEYBOARDTYPE,
    RETURNKEYTYPE,
    ISCLEARONBEGINEDITTING,
    BORDERSTYLE,
    COLOR,
    PATH,
    MAXROWS,
    HINTTEXTLABLE,
    MAXLENGTH,
    AOTOWRAP,
    FIREDATE,
    TIMEZONE,
    SOUNDNAME,
    ALERTBODY,
    APPLICATIONICONBADGENUMBER,
    USERINFO,
    ISON,
    ONTINTCOLOR,
    THUMBTINTCOLOR,
    
#pragma mark - segment
    ITEMS,
    CHECKICON,//可去掉
    UNCHECKICON,//可去掉
    CHECKEDITEMCOLOR,
    SEGMENTS, //可去掉
    CHECKEDITEM,

    
    FONT,
    ANIMATION,
    NORMALTEXTCOLOR,
    HIGHLIGHTTEXTCOLOR,
    CURRENTSELETEDSEGMENTINDEXT,
    BARSTYLE,
    PLACEHOLDER,
    BACKGROUNDIMAGE,
    URL,
    URLRIGHT,
    CONTENTSIZE,
    CONTENTOFFSET,
    INDICATORSTYLE,
    BOUNCES,
    PAGINGENABLED,
    SCROLLENABLED,
    SHOWSHORIZONTALSCROLLINDICATOR,
    SHOWSVERTICALSCROLLINDICATOR,
    OVERFLOWINDICATOR,
    IMAGEVIEW,
    VALUE,
    PROGRESSBARTYPE,
    FINISHEDCOLOR,
    UNFINISHEDCOLOR,
    SLIDERBACKGROUND,
    PROGRESSBAR,
    SEEKBAR,
    MAXVALUE,
    MINVALUE,
    ISCHECKED,
    ISBACK,
    SHOWBACK,
    TITLE,
    TIME,   //时间
    NUMSTAR,
    HIGHSTARIMG,
    STARIMG,
    RATING,
    ENABLED,
    CONTENT,
    MASSAGE,
    CANCELBUTTON,
    OTHERBUTTONTITLES,
    ISSHOWMENU,
    MENUARRAY,
    ONTEXT,
    OFFTEXT,
    PLACE,
    FORMAT,
    MINDATE,
    MAXDATE,
    NOWDATE,
    NOWTIME,
    MINTIME,
    MAXTIME,
    MINNUM,
    MAXNUM,
    DEFAULTNUM,
    COUNT,
    ADDMRView,
    COLUMNS,
    ROWHEIGHT,
    ADJUSTPAN,
    EFFECT,
    PINCHGESTURE,
    SWIPEGESTURE,
    SHOWDIVIDER,
    STATE,
    UNDERLINE,
    JUMPTO,
    ALPHA,
    STATUSBARSTYLE,
    INTERVAL,
#pragma mark- For MRTabBar
    BADGE,
    BADGEFILLCOLOR,
    BADGETEXTCOLOR,
    BADGEBORDERCOLOR,
#pragma -mark For LinearLayout
    ALIGN,
    WEIGHT,
    WEIGHTSUM,
    HORIZONGAP,
    VERTICALGAP,
    MARGINGAP,
    TITLES,
    IMAGES,
    ITEMIMAGES,
    PADDINGTOP,
    PADDINGRIGHT,
    PADDINGLEFT,
    PADDINGBOTTOM,
    MARGINTOP,
    MARGINRIGHT,
    MARGINBOTTOM,
    MARGINLEFT,
    GRAVITYHORIZONTAL,
    GRAVITYVERTICAL,
    NAVIGATIONBAR,
#pragma -mark ListView
    DATASOURCE,
    TEMPLATESELECTFILTER,
    TEMPLATESELECTFIELD,
    SELECTFILTER,
    VIEWES,
    STOP,
    STRETCH,
    SELECTED,
    CURRENTINDEX,
    INPUTTYPE,
    RADIOBUTTON,
    GROUPBY,
    INDEXER,
    MENUITEM,
    MENU,
    SECTIONHEADERVISIBLE,
    SHOWINDEXER,
    EXPANDABLE,
    CONTROLLER,
    MENUITEMTITLE,
    MENUITEMSHOWASACTIONBAR,
    ICON,
    SELECTEDIMAGE,
    MENUFILTER,
    LAYOUTGRAVITY,
    ITEMBACKGROUND,
    BACKGROUNDCOLOR,
    HEADERVIEW,
    DIVIDERCOLOR,
    
    
    
    
    BUNDLE,
    HINT_WIDTH,
    HINT_HEIGHT,
    TEXTUNDERLINE,
    
#pragma mark -MRWebView
    SRC,
    CACHEABLE,
    SAFEABLE,
    
#pragma mark - MRChronomater
    COUNTSTYLE,
    TIMEFORMAT,
    TIMEINTERVAL,
    STARTTIME,
    ENDTIME,
    
#pragma mark -地图属性
    MAPTYPE,
    SHOWSUSERLOCATION,
    ZOOMENABLED,
    ROTATIONENABLED,
    TRAFFICENABLED,
    CENTERCOORDINATE,
    ZOOMLEVEL,
    MAPSWITCHLIST,
#pragma mark -chart view
    CHARTDATA,
    CHARTTYPE,
    //    CHARTTITLE,
    TITLETEXT,
    //    TITLECOLOR,
    //    TITLEFONTSIZE,
    CHARTCOLORS,
    XLABELS,
    LEGENDVISIBLE,
    LEGENDDESCRIPTION,
    
#pragma -mark autoCompeleteTextView 属性
    DROPDOWNROWS,
    DROPDOWNHEIGHT,
    MINNUMBER,
    LABELFIELD,
    
#pragma -mark For ViewPaper -- added by tyj
    AUTOPLAY,//轮播开关
    PLAYINTERVAL,//轮播间隔时间
    PLAYDURATION,//轮播时间每个界面切换动画时间
    DETAILURLS,
    
#pragma mark - SmartLayout
    ATTR_TOP_VIEW,
    ATTR_BOTTOM_VIEW,
    ATTR_LEFT_VIEW,
    ATTR_RIGHT_VIEW,
    
    ATTR_TOP,
    ATTR_BOTTOM,
    ATTR_LEFT,
    ATTR_RIGHT,
    ATTR_CENTER_X,
    ATTR_CENTER_Y,
    
#pragma mark - FlexLayout
    FLEX_DISPLAY,
    FLEX_DIRECTION,
    FLEX_CONTENTJUSTIFICATION,
    FLEX_ITEMSALIGNMENT,
    FLEX_ALIGNMENT,
    FLEX_POSITIONTYPE,
    FLEX_WRAP,
    FLEX_FLOAT,
    FLEX_MARGIN,
    FLEX_POSITION,
    FLEX_PADDING,
    FLEX_BORDER,
    FLEX_SIZE,
    
#pragma mark - adapter IDE
    BACKGROUND_NORMAL,
    EFFECTCOMPLETEDIMAGE,
    BACKGROUND_DISABLE,
    BACKGROUND_PRESSED,
    BACKGROUND_CHECKED,
    
    ICON_NORMAL,
    ICON_PRESSED,
    ICON_DISABLE,
    ICON_CHECKED,
    TEXTCOLOR_NORMAL,
    TEXTCOLOR_PRESSED,
    TEXTCOLOR_CHECKED,
    TEXTCOLOR_DISABLE,
    INDEX,
    HINTTEXTCOLOR,
    TYPE,
    CLEARINPUTICON,
    PULLSTARTLABEL,
    PULLSTARTRELEASELABEL,
    PULLSTARTRELEASELABELTEXTSIZE,
    PULLSTARTRELEASELABELTEXTCOLOR,
    
    PULLSTARTREFRESHINGICON,
    PULLSTARTREFRESHINGLABELTEXTSIZE,
    PULLSTARTREFRESHINGLABELTEXTCOLOR,
    

    
    PULLSTARTUPDATELABEL,
    PULLSTARTUPDATELABELTEXTSIZE,
    PULLSTARTUPDATELABELTEXTCOLOR,
    
    
    
    PULLSTARTREFRESHINGLABEL,
    PULLSTARTICON,
    PULLENDICON,
    PULLSTARTLABELTEXTCOLOR,
    PULLENDLABEL,
    PULLENDLABELTEXTCOLOR,
    PULLSTARTMIDDLEREFRESHINGICON,
    PULLENDMIDDLEREFRESHINGICON,

    PULLSTARTLABELTEXTSIZE,
    PULLENDLABELTEXTSIZE,
    
    SCROLLBARSHORIZONTAL,
    SCROLLBARSVERTICAL,
    
    PULLSTARTLOADINGFINISHEDLABEL,
    PULLSTARTLOADINGFINISHEDLABELTEXTSIZE,
    PULLSTARTLOADINGFINISHEDLABELTEXTCOLOR,
    
    PULLSTARTPULLREFRESHMODE,
    
    PULLENDRELEASELABEL,
    PULLENDRELEASELABELTEXTSIZE,
    PULLENDRELEASELABELTEXTCOLOR,
    
    PULLENDREFRESHINGICON,
    PULLENDREFRESHINGLABEL,
    PULLENDREFRESHINGLABELTEXTSIZE,
    PULLENDREFRESHINGLABELTEXTCOLOR,
    

    PULLENDUPDATELABEL,
    PULLENDUPDATELABELTEXTSIZE,
    PULLENDUPDATELABELTEXTCOLOR,
    
    PULLENDLOADINGFINISHEDLABEL,
    PULLENDLOADINGFINISHEDLABELTEXTSIZE,
    PULLENDLOADINGFINISHEDLABELTEXTCOLOR,

    
   
    PULLENDREFRESHMODE,
    
    FOOTERDIVIDERSENABLED,
    



 

    

#pragma mark - CalendarView
    BEGINDATE,
    ENDDATE,
    SELECTEDDATE,
    TITLECLICKTYPE,
    
    TITLEBACKGROUND,
    TITLETEXTCOLOR,
    TITLETEXTSIZE,
    FORWARDICON,
    BACKWARDICON,
    
    CALENDARTEXTSIZE,
    
    SELECTEDDATETEXTCOLOR,
    SELECTEDDATEBACKGROUND,
    TODAYTEXTCOLOR,
    TODAYBACKGROUND,
    WEEKENDTEXTCOLOR,
    WEEKENDBACKGROUND,
    OTHERDATETEXTCOLOR,
    OTHERDATEBACKGROUND,
    DISABLEDATETEXTCOLOR,
    DISABLEDATEBACKGROUND,
    WORKDAYTEXTCOLOR,
    WORKDAYBACKGROUND,
    DEFAULTIMAGE,
    SELECTEDATE,
    TITLEBGCOLOR,
    SELECTEDTEXTCOLOR,
    SELECTEDBGCOLOR,
    TODAYBGCOLOR,
    WEEKENDBGCOLOR,
    OTHERTEXTCOLOR,
    OTHERBGCOLOR,
    DISABLETEXTCOLOR,
    DISABLEBGCOLOR,
    WORKDAYBGCOLOR,
    
#pragma makr - actionBar
    BACKIMAGENORMAL,
    BACKIMAGEPRESSED,
    
    SEARCHVIEWICON,
    HTTPHEADERS,
    DISPLAYPASSWORD,
#pragma mark - searchView
    
    SHOWSEARCHBUTTON,
    
    
    
    
    TEXTSIZENORMAL,
    DEFAULTDATE,
#pragma mark - selectView
    SELECTICON,
    LISTTEXTSELECTCOLOR,
    DROPDOWNLISTTEXTSIZE,
    DROPDOWNLISTTEXTCOLOR,
    MINWIDTH,
#pragma mark - progressBar
    TEXTVISIBLE,
    
#pragma mark - label
    ELLIPSIZE,
    MAXWIDTH,
    MAXHEIGHT,
#pragma mark - pickerView
    DEFAULTVALUE,
    VALUES,

#pragma mark - timePicker
    DEFAULTTIME,
#pragma mark - scrollView
    SHOWSCROLLBARS,
    
} propertyKeysAndValue;

@interface PropertiesManager : NSObject

@property(nonatomic,readonly,strong)NSMutableDictionary* properties;

+ (instancetype)shareInstance;

@end
